const KEY="attandace_pro_v5";
const days=["Monday","Tuesday","Wednesday","Thursday","Friday","Saturday","Sunday"];
const today=()=>new Date().toISOString().slice(0,10);
const uid=()=>crypto.randomUUID?crypto.randomUUID():Math.random().toString(36).slice(2)+Date.now();
let data=JSON.parse(localStorage.getItem(KEY)||"null")||{subjects:[],records:{},holidays:{},schedule:[],settings:{name:"",minPct:75,semester:""}};
data.holidays??={};data.schedule??=[];data.settings??={name:"",minPct:75,semester:""};
function save(){localStorage.setItem(KEY,JSON.stringify(data));render()}
function esc(x){return String(x??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]))}
function subject(id){return data.subjects.find(s=>s.id===id)}
function minFor(s){return +(s.min||data.settings.minPct||75)}
function percent(s){let t=s.present+s.absent;return t?100*s.present/t:0}
function level(p,m=minFor({})){return p<m?["bad","Danger"]:p<m+5?["warn","Caution"]:["good","Safe"]}
function toast(t){let x=document.getElementById("toast");x.textContent=t;x.classList.add("show");setTimeout(()=>x.classList.remove("show"),1800)}
function mark(id,val,date){if(data.holidays[date]){toast("This date is a holiday");return}let s=subject(id);if(!s)return;data.records[date]??={};let old=data.records[date][id];if(old===true)s.present--;if(old===false)s.absent--;data.records[date][id]=val;if(val===true)s.present++;else s.absent++;save();toast(val?"Present marked":"Absent marked")}
function holiday(d){return data.holidays[d]}
function openModal(type,id=null){
 const m=document.getElementById("modal"),f=document.getElementById("form");m.classList.remove("hidden");
 if(type==="subject"){let s=id&&subject(id);document.getElementById("modalTitle").textContent=id?"Edit subject":"Add subject";f.innerHTML=`<div class="form"><label>Subject name<input id="fName" required value="${esc(s?.name||"")}"></label><label>Short code<input id="fCode" value="${esc(s?.code||"")}"></label><label>Minimum attendance %<input id="fMin" type="number" min="1" max="100" value="${s?.min||data.settings.minPct}"></label><label>Teacher (optional)<input id="fTeacher" value="${esc(s?.teacher||"")}"></label><label>Room (optional)<input id="fRoom" value="${esc(s?.room||"")}"></label><label>Initial present<input id="fP" type="number" min="0" value="${s?.present||0}"></label><label>Initial absent<input id="fA" type="number" min="0" value="${s?.absent||0}"></label><button class="primary" type="submit">Save subject</button></div>`;
 f.onsubmit=e=>{e.preventDefault();let n=document.getElementById("fName").value.trim();if(!n)return;let obj={name:n,code:document.getElementById("fCode").value.trim().toUpperCase(),min:+document.getElementById("fMin").value||75,teacher:document.getElementById("fTeacher").value.trim(),room:document.getElementById("fRoom").value.trim(),present:+document.getElementById("fP").value||0,absent:+document.getElementById("fA").value||0};if(id)Object.assign(s,obj);else data.subjects.push({id:uid(),...obj});m.classList.add("hidden");save();toast(id?"Subject updated":"Subject added")}}
 if(type==="holiday"){document.getElementById("modalTitle").textContent="Add holiday";f.innerHTML=`<div class="form"><label>Date<input id="fDate" type="date" required value="${id||today()}"></label><label>Holiday name<input id="fHName" required placeholder="Independence Day"></label><label>Type<select id="fHType"><option value="full">Full day</option><option value="half">Half day</option></select></label><button class="primary" type="submit">Save holiday</button></div>`;f.onsubmit=e=>{e.preventDefault();let d=document.getElementById("fDate").value;if(!d)return;data.holidays[d]={name:document.getElementById("fHName").value.trim(),type:document.getElementById("fHType").value};m.classList.add("hidden");save();toast("Holiday saved")}}
 if(type==="class"){document.getElementById("modalTitle").textContent="Add timetable class";f.innerHTML=`<div class="form"><label>Day<select id="fDay">${days.slice(0,6).map(d=>`<option>${d}</option>`).join("")}</select></label><label>Subject<select id="fSub">${data.subjects.map(s=>`<option value="${s.id}">${esc(s.name)}</option>`).join("")}</select></label><label>Start<input id="fStart" type="time" required></label><label>End<input id="fEnd" type="time"></label><label>Room<input id="fCRoom" placeholder="Room 204"></label><button class="primary" type="submit">Save class</button></div>`;f.onsubmit=e=>{e.preventDefault();data.schedule.push({id:uid(),day:document.getElementById("fDay").value,subjectId:document.getElementById("fSub").value,start:document.getElementById("fStart").value,end:document.getElementById("fEnd").value,room:document.getElementById("fCRoom").value});m.classList.add("hidden");save();toast("Class added")}}
}
function delSubject(id){if(confirm("Delete subject and its records?")){data.subjects=data.subjects.filter(s=>s.id!==id);Object.values(data.records).forEach(r=>delete r[id]);data.schedule=data.schedule.filter(x=>x.subjectId!==id);save();toast("Subject deleted")}}
function delHoliday(d){if(confirm("Delete this holiday?")){delete data.holidays[d];save();toast("Holiday deleted")}}
function delClass(id){data.schedule=data.schedule.filter(x=>x.id!==id);save();toast("Class removed")}
function todayName(){return ["Sunday","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"][new Date().getDay()]}
function renderHome(){
 let total=data.subjects.reduce((a,s)=>a+s.present+s.absent,0),pr=data.subjects.reduce((a,s)=>a+s.present,0),ab=total-pr,p=total?100*pr/total:0,m=+data.settings.minPct||75,[c,st]=level(p,m);
 document.getElementById("hello").textContent=data.settings.name?`Hello, ${data.settings.name} 👋`:"Hello 👋";document.getElementById("todayText").textContent=`${todayName()} • ${new Date().toLocaleDateString(undefined,{day:"numeric",month:"short",year:"numeric"})}${data.settings.semester?" • "+data.settings.semester:""}`;
 document.getElementById("overall").textContent=p.toFixed(1)+"%";document.getElementById("gaugePct").textContent=p.toFixed(1)+"%";document.getElementById("overallBadge").textContent=total?`${st} • minimum ${m}%`:"Add subjects";document.getElementById("present").textContent=pr;document.getElementById("absent").textContent=ab;document.getElementById("total").textContent=total;
 let deg=Math.min(360,p*3.6);document.getElementById("gauge").style.background=`conic-gradient(var(--accent),var(--cyan) ${deg}deg,#252a35 ${deg}deg)`;
 document.getElementById("overallHint").textContent=total?(p<m?`You are ${(m-p).toFixed(1)} points below your minimum.`:`Keep going — your attendance is currently ${p.toFixed(1)}%.`):"Add your subjects to start tracking.";
 let alert=document.getElementById("alert");alert.className="alert"+(p<m?" bad":"")+(total?"":" hidden");if(total)alert.innerHTML=p<m?`🔴 <b>Attendance below minimum.</b> Prioritize ${data.subjects.filter(s=>percent(s)<minFor(s)).length} subject(s) before the next shortage.`:`🟢 <b>${st}.</b> Check the Planner before missing a class.`;
 let streak=Object.keys(data.records).sort().reverse().findIndex(d=>data.records[d]&&Object.values(data.records[d]).includes(true));document.getElementById("streak").textContent=streak<0?0:streak+1;
 let arr=data.subjects.slice().sort((a,b)=>percent(a)-percent(b));document.getElementById("attentionCards").innerHTML=arr.slice(0,4).map(subjectCard).join("")||empty("No subjects yet","Add subjects to see smart warnings.");
 let sched=data.schedule.filter(x=>x.day===todayName()).sort((a,b)=>a.start.localeCompare(b.start));document.getElementById("todayCards").innerHTML=sched.length?sched.map(x=>scheduleCard(x)).join(""):data.subjects.slice(0,4).map(s=>markCard(s,today())).join("")||empty("Nothing scheduled","Add subjects or a timetable.");
}
function empty(a,b){return `<div class="card"><div class="main"><b>${a}</b><small>${b}</small></div></div>`}
function subjectCard(s){let p=percent(s),[c,st]=level(p,minFor(s));return `<div class="card"><div class="dot ${c}"></div><div class="main"><b>${esc(s.name)}</b><small>${esc(s.teacher||"")} ${s.room?"• "+esc(s.room):""} • ${s.present}/${s.present+s.absent} present • min ${minFor(s)}%</small></div><div class="pct">${p.toFixed(1)}%</div><div class="actions"><button onclick="openModal('subject','${s.id}')">Edit</button><button onclick="delSubject('${s.id}')">×</button></div></div>`}
function markCard(s,d){let v=data.records[d]?.[s.id];return `<div class="card"><div class="dot ${level(percent(s),minFor(s))[0]}"></div><div class="main"><b>${esc(s.name)}</b><small>${percent(s).toFixed(1)}% • ${v===true?"Marked present":v===false?"Marked absent":"Not marked"}</small></div><div class="actions"><button onclick="mark('${s.id}',true,'${d}')">✓</button><button onclick="mark('${s.id}',false,'${d}')">✕</button></div></div>`}
function scheduleCard(x){let s=subject(x.subjectId);return s?`<div class="card"><div class="main"><b>${esc(s.name)}</b><small>${x.start}${x.end?"–"+x.end:""} ${x.room?"• "+esc(x.room):""}</small></div><div class="actions"><button onclick="mark('${s.id}',true,'${today()}')">Present</button><button onclick="mark('${s.id}',false,'${today()}')">Absent</button></div></div>`:""}
function renderSubjects(){document.getElementById("subjectsList").innerHTML=data.subjects.map(subjectCard).join("")||empty("No subjects","Add your first subject.")}
function renderMark(){let d=document.getElementById("markDate").value||today(),hb=document.getElementById("holidayBanner"),h=holiday(d);hb.innerHTML=h?`<div class="holidayNotice">🏖️ <b>${esc(h.name)}</b> — ${h.type==="half"?"Half day":"Full day"} holiday. Attendance is disabled for this date.</div>`:"";document.getElementById("markList").innerHTML=data.subjects.map(s=>markCard(s,d)).join("")||empty("No subjects","Add subjects first.")}
function renderTimetable(){let active=document.querySelector(".day.active")?.dataset.day||todayName();document.getElementById("days").innerHTML=days.slice(0,6).map(d=>`<button class="day ${d===active?"active":""}" data-day="${d}"><b>${d.slice(0,3)}</b><small>${data.schedule.filter(x=>x.day===d).length} classes</small></button>`).join("");document.querySelectorAll(".day").forEach(b=>b.onclick=()=>{document.querySelectorAll(".day").forEach(x=>x.classList.remove("active"));b.classList.add("active");renderTimetable()});let list=data.schedule.filter(x=>x.day===active).sort((a,b)=>a.start.localeCompare(b.start));document.getElementById("scheduleList").innerHTML=list.map(x=>`<div class="card"><div class="main"><b>${esc(subject(x.subjectId)?.name||"Unknown")}</b><small>${x.start}${x.end?"–"+x.end:""} ${x.room?"• "+esc(x.room):""}</small></div><div class="actions"><button onclick="delClass('${x.id}')">Delete</button></div></div>`).join("")||empty("No classes","Add a class to this day.")}
function renderHolidays(){let ds=Object.keys(data.holidays).sort(),future=ds.find(d=>d>=today()),nh=document.getElementById("nextHoliday"),ns=document.getElementById("nextHolidaySub");if(future){nh.textContent=data.holidays[future].name;ns.textContent=`${future} • ${data.holidays[future].type==="half"?"Half day":"Full day"}`}else{nh.textContent="No upcoming holiday";ns.textContent="Add your college holidays below."}document.getElementById("holidayList").innerHTML=ds.map(d=>{let h=data.holidays[d];return `<div class="card"><div class="main"><b>${esc(h.name)}</b><small>${d} • ${h.type==="half"?"Half day":"Full day"} • excluded from attendance</small></div><div class="actions"><button onclick="openModal('holiday','${d}')">Edit</button><button onclick="delHoliday('${d}')">Delete</button></div></div>`}).join("")||empty("No holidays","Tap ＋ Holiday to add one.")}
function renderHistory(){let ds=Object.keys(data.records).sort().reverse();document.getElementById("historyList").innerHTML=ds.map(d=>{let r=data.records[d],rows=Object.entries(r).map(([id,v])=>subject(id)?`<div class="row"><span>${esc(subject(id).name)}</span><b>${v?"Present":"Absent"}</b></div>`:"").join("");return `<div class="historyday"><strong>${d}</strong>${rows}</div>`}).join("")||empty("No attendance history","Mark your first class.")}
function options(id){document.getElementById(id).innerHTML=`<option value="">Select subject</option>`+data.subjects.map(s=>`<option value="${s.id}">${esc(s.name)}</option>`).join("")}
function planner(){
 ["missSubject","recoverSubject","marginSubject"].forEach(options);
 let s=subject(document.getElementById("missSubject").value);if(s){let m=minFor(s),after=100*s.present/(s.present+s.absent+1);document.getElementById("missResult").innerHTML=after>=m?`🟢 You can miss 1 class and stay at <b>${after.toFixed(1)}%</b>.`:`⚠️ <b>Don't miss.</b> You would fall to ${after.toFixed(1)}%, below your ${m}% minimum.`}else document.getElementById("missResult").textContent="Choose a subject.";
 s=subject(document.getElementById("recoverSubject").value);if(s){let m=minFor(s)/100,n=0;while((s.present+n)/(s.present+s.absent+n)<m&&n<10000)n++;document.getElementById("recoverResult").innerHTML=(percent(s)>=minFor(s)?`🟢 Already above minimum at ${percent(s).toFixed(1)}%.`:`📚 Attend the next <b>${n}</b> consecutive class${n===1?"":"es"} to reach ${minFor(s)}%.`)}else document.getElementById("recoverResult").textContent="Choose a subject.";
 s=subject(document.getElementById("marginSubject").value);if(s){let m=minFor(s)/100,n=0;while((s.present)/(s.present+s.absent+n)>=m&&n<10000)n++;document.getElementById("marginResult").innerHTML=`🛡️ Safe absence margin: <b>${Math.max(0,n-1)}</b> class${Math.max(0,n-1)===1?"":"es"} before dropping below ${minFor(s)}%.`}else document.getElementById("marginResult").textContent="Choose a subject.";
}
function renderStats(){let a=data.subjects.slice().sort((x,y)=>percent(y)-percent(x)),w=a.slice().sort((x,y)=>percent(x)-percent(y));document.getElementById("bestSubject").textContent=a[0]?`${a[0].name} • ${percent(a[0]).toFixed(1)}%`:"—";document.getElementById("worstSubject").textContent=w[0]?`${w[0].name} • ${percent(w[0]).toFixed(1)}%`:"—";let month=new Date().toISOString().slice(0,7),mc=Object.entries(data.records).filter(([d])=>d.startsWith(month)).reduce((n,[,r])=>n+Object.keys(r).length,0);document.getElementById("monthClasses").textContent=mc;document.getElementById("goalText").textContent=data.settings.minPct+"%";document.getElementById("bars").innerHTML=a.map(s=>`<div class="bar"><div class="barhead"><span>${esc(s.name)}</span><b>${percent(s).toFixed(1)}%</b></div><div class="barline"><div class="barfill" style="width:${Math.min(100,percent(s))}%"></div></div></div>`).join("")||empty("No data","Add subjects.")}
function renderSettings(){document.getElementById("studentName").value=data.settings.name;document.getElementById("minPct").value=data.settings.minPct;document.getElementById("semester").value=data.settings.semester}
function render(){renderHome();renderSubjects();renderMark();renderTimetable();renderHolidays();renderHistory();planner();renderStats();renderSettings()}
function nav(id){document.querySelectorAll(".page").forEach(p=>p.classList.toggle("active",p.id===id));document.querySelectorAll(".nav button").forEach(b=>b.classList.toggle("active",b.dataset.page===id));render()}
document.querySelectorAll("[data-page]").forEach(b=>b.onclick=()=>nav(b.dataset.page));
document.getElementById("addSubject").onclick=()=>openModal("subject");document.getElementById("addHoliday").onclick=()=>openModal("holiday");document.getElementById("addClass").onclick=()=>data.subjects.length?openModal("class"):toast("Add a subject first");document.getElementById("close").onclick=()=>document.getElementById("modal").classList.add("hidden");document.getElementById("markDate").value=today();document.getElementById("markDate").onchange=renderMark;
["missSubject","recoverSubject","marginSubject"].forEach(id=>document.getElementById(id).onchange=planner);
document.getElementById("studentName").onchange=e=>{data.settings.name=e.target.value.trim();save()};document.getElementById("minPct").onchange=e=>{data.settings.minPct=Math.max(1,Math.min(100,+e.target.value||75));save();toast("Minimum updated")};document.getElementById("semester").onchange=e=>{data.settings.semester=e.target.value.trim();save()};
document.getElementById("themeBtn").onclick=()=>{document.documentElement.classList.toggle("light");localStorage.setItem("v5theme",document.documentElement.classList.contains("light")?"light":"dark")};if(localStorage.getItem("v5theme")==="light")document.documentElement.classList.add("light");
document.getElementById("clearHistory").onclick=()=>{if(confirm("Clear all attendance records and reset subject totals?")){data.records={};data.subjects.forEach(s=>{s.present=0;s.absent=0});save();toast("History cleared")}};
document.getElementById("export").onclick=()=>{let a=document.createElement("a");a.href=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:"application/json"}));a.download="attandace-pro-v5-backup.json";a.click();URL.revokeObjectURL(a.href)};
document.getElementById("import").onchange=e=>{let f=e.target.files[0];if(!f)return;let r=new FileReader();r.onload=()=>{try{let x=JSON.parse(r.result);if(!x.subjects||!x.records)throw 0;data=x;data.holidays??={};data.schedule??=[];save();toast("Backup restored")}catch{alert("Invalid backup file")}};r.readAsText(f)};
document.getElementById("reset").onclick=()=>{if(confirm("Reset ALL subjects, attendance, holidays and timetable?")){localStorage.removeItem(KEY);location.reload()}};
document.getElementById("demo").onclick=()=>{data={subjects:[{id:uid(),name:"Python",code:"PY",min:75,teacher:"Prof. Sharma",room:"204",present:18,absent:2},{id:uid(),name:"DBMS",code:"DB",min:75,teacher:"Prof. Patil",room:"205",present:16,absent:4},{id:uid(),name:"Computer Networks",code:"CN",min:75,teacher:"Prof. Jadhav",room:"301",present:17,absent:5}],records:{},holidays:{[today()]:{name:"Sample College Holiday",type:"full"}},schedule:[],settings:{name:"Tanmay",minPct:75,semester:"Semester 5"}};save();toast("Sample data loaded")};
document.getElementById("notifyBtn").onclick=async()=>{if(!("Notification"in window)){toast("Notifications not supported here");return}let p=await Notification.requestPermission();toast(p==="granted"?"Notifications enabled":"Notification permission not granted")};
if("serviceWorker"in navigator)window.addEventListener("load",()=>navigator.serviceWorker.register("sw.js").catch(()=>{}));
render();